# Generated by Django 4.2.7 on 2024-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_user_member_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
