# Generated by Django 4.2.7 on 2024-04-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_room_hostel_alter_customersupport_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharing_type',
            fields=[
                ('sharings', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('sharing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.sharing_type')),
            ],
        ),
    ]
